Numpy array с элементами от числа N до 0

In [14]:
import numpy as np

In [15]:
N=int(input())
x=np.arange(N-1, -1, -1)
print(x)

10
[9 8 7 6 5 4 3 2 1 0]


Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму её значений на диагонали.

In [16]:
N=int(input())
mat=np.diag(np.arange(N-1, -1, -1)) 
print(mat)
print('сумма: {}'.format(sum(sum(mat))))

10
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
сумма: 45


Решите систему уравнений:

4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [17]:
from numpy import linalg

In [18]:
a=np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b=np.array([4, 12, -3])
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [19]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True